ARG JUPYTER_DEBIAN_VERSION="1.0.0"

FROM xandai/jupyter-debian:${JUPYTER_DEBIAN_VERSION}

ARG JUPYTER_USER="jupyter"

ARG NUMPY_VERSION='1.16.2'
ARG PANDAS_VERSION='0.24.1'
ARG SCIKIT_LEARN_VERSION='0.20.3'
ARG IMAGEIO_VERSION='2.5.0'
ARG MATPLOTLIB_VERSION='3.0.3'
ARG SEABORN_VERSION='0.9.0'

ARG PIP_PACKAGES="\
numpy==${NUMPY_VERSION} \
pandas==${PANDAS_VERSION} \
scikit-learn==${SCIKIT_LEARN_VERSION} \
imageio==${IMAGEIO_VERSION} \
matplotlib==${MATPLOTLIB_VERSION} \
seaborn==${SEABORN_VERSION} \
"

USER root

RUN python -m pip install --no-cache-dir ${PIP_PACKAGES}

USER ${JUPYTER_USER}
